import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/1.png";
import Image from "next/image";
import web1 from "../public/beautysalon1.png";
import web2 from "../public/travel1.png";
import web3 from "../public/champions1.png";
import web4 from "../public/tcc.jpeg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">DevelopedByIgor</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Igor Borges
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Desenvolvedor Web
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Sou um desenvolvedor com foco na criação e desenvolvimento de sistemas. Sou extremamente motivado para adquirir conhecimento e aprimorar minhas Skills!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.instagram.com/ig0r_b0rges/" target="_blank" rel="noreferrer"> <AiFillInstagram /></a>
              <a href="https://www.linkedin.com/in/igorborges812/" target="_blank" rel="noreferrer"> <AiFillLinkedin /></a>
              <a href="https://github.com/igorborges812" target="_blank" rel="noreferrer"> <AiFillGithub /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfólio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Desde o início da minha jornada como desenvolvedor, desenvolvi alguns projetos pessoais que contribuiram para a evolução das minhas skills até o presente momento.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Aqui estão alguns dos meus projetos.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="https://gentle-mermaid-1e264e.netlify.app" target="_blank" rel="noreferrer">
                <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href=" https://verdant-medovik-74fa29.netlify.app" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://jolly-kangaroo-53245a.netlify.app" target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              /> </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/igorborges812/TCC--IFC" target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              /></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
